name: Trigger auto deployment for automacao-ar

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/automacao-ar-AutoDeployTrigger-2a704be5-e37e-4d6e-81b7-d84414ff7772.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AUTOMACAOAR_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: carolcontainers.azurecr.io
          registryUsername: ${{ secrets.AUTOMACAOAR_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AUTOMACAOAR_REGISTRY_PASSWORD }}
          containerAppName: automacao-ar
          resourceGroup: carol
          imageToBuild: carolcontainers.azurecr.io/automacao-ar:${{ github.sha }}
          

     

